### ISSUE TITLE
Unexpected Token Error When Creating AST with Lua Code Containing the "//" Operator

### ISSUE THREAD

**Issue by lynnlake** [evaera/moonwave#129]
the error msg is:
```
error occurred while creating ast: unexpected token `/`
```

It is worth noting that the "//" operator was only introduced to Lua in version 5.3. In order to reproduce this error, you can use the following code snippet:

```lua
p = 3.0
p = p and p // 1
```
Please note that this error appears to be related to the parser, as it is unable to recognize the "//" operator.

**Comment by evaera** [comment]
We currently only support Lua 5.1/Luau mode but the underlying parser we use (full_moon) does support Lua 5.2, 5.3, and 5.4. 

We would need to add a flag/config option to Moonwave to allow selecting which version of Lua to use to support this.

**Comment by RuizuKun-Dev** [comment]
Hey, 👋🏻 

I'm currently affected by this, I was wondering when will the update be released?

**Comment by YetAnotherClown** [comment]
Hello @RuizuKun-Dev, I gave a brief answer on Discord but I will also provide an answer here in case anyone else comes across this.

This issue would be fixed by updating full-moon to v0.19.0, which is the version I was originally going to update Moonwave to. Unfortunately, I was experiencing full-moon crashes on that version in large codebases during testing, such as Nevermore. These crashes are fixed in full-moon v1.0.0 which is not out *just yet*.

Since I do not want to break workflows for projects such as Nevermore, this is currently blocked until the release of full-moon v1.0.0 which, to my knowledge, has no ETA but is currently in pre-release phase and should hopefully be released soon.

In the meantime, you can instead do
```luau
-- This
math.floor(a / b)

-- Instead of
a // b
```

For future tracking, see #147.

**Comment by RuizuKun-Dev** [comment]
ahhh, okay thank you for the answer appreciate it! 🙏🏻 @YetAnotherClown 

> In the meantime, you can instead do
> 
> ```luau
> -- This
> math.floor(a / b)
> 
> -- Instead of
> a // b
> ```

yeah, I actually did that for bufferUtil

**Comment by myzhan** [comment]
What about build extractor with features?

 cargo install --path . --locked --features "full_moon/lua54"

**Comment by myzhan** [comment]
I'm still affected by this, after updating full-moon to 2.0.0.

See: https://github.com/Kampfkarren/full-moon/issues/341
